site_name: café e bola
site_url: https://site.example
copyright: copyright &copy; 2025 marina caponera
extra:
  social:
    - icon: simple/bluesky
      link: https://bsky.app/profile/mcaponera.bsky.social
    - icon: simple/github
      link: https://github.com/mcaponera

nav:
  - peneira spider:
    - é o que: index.md
    - configurações: configuracoes.md
    - objeto da raspagem: paginas_raspagem.md
  - blog: blog/index.md

plugins:
  - blog:
      enabled: true
      blog_dir: blog

theme:
  language: pt-BR
  features:
    - navigation.footer
    - navigation.indexes
  icon:
    logo: material/chart-ppf
  name: material
  palette: 
    # dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: modo escuro
      primary: red
      accent: teal 

    # light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: modo claro
      primary: red
      accent: teal

  font:
    text: Fira Sans
    code: Fira Code
  
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - admonition
  - pymdownx.details
  - toc:
      title: nessa página
